name       : partitionmanager
version    : 20.12.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/partitionmanager-20.12.0.tar.xz : 77e9edb7fac1f0a1798c0dcf1a422f4dabb710921a9026b4e1e06803ee2be31e
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(libatasmart)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpmcore-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
