name       : partitionmanager
version    : 23.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/partitionmanager-23.04.2.tar.xz : 51aa023451b9ba8e8bff7833976079efc9eb8b97db03ecd3dc16c644b8a1fcec
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(libatasmart)
    - pkgconfig(polkit-qt5-1)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kpmcore-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove HTML docs
    rm -rf $installdir/usr/share/doc
