name       : partitionmanager
version    : 3.3.1
release    : 3
source     :
    - https://cdn.download.kde.org/stable/partitionmanager/3.3.1/src/partitionmanager-3.3.1.tar.xz : 5107955f9c70fc859bef04a54bffb28cd50efe355694232b9860e9d9c97a0f4a
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(gl)
    - pkgconfig(libatasmart)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpmcore-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pkexec-to-launch-PartitionManager.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m 00644 $pkgfiles/com.solus_project.pkexec.partitionmanager.policy $installdir/usr/share/polkit-1/actions/com.solus_project.pkexec.partitionmanager.policy
