name       : partitionmanager
version    : 4.0.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/partitionmanager/4.0.0/src/partitionmanager-4.0.0.tar.xz : 7967edaf9dad3641ff31ff5da1f23578c7348e3d70214baf16236d5c40c413e1
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(gl)
    - pkgconfig(libatasmart)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpmcore-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
