name       : partitionmanager
version    : 22.08.3
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/partitionmanager-22.08.3.tar.xz : f924ec295fc1ee8e4477295291e7481fac6b0b0f94b687667cd160ca0e51abb3
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(libatasmart)
    - pkgconfig(polkit-qt5-1)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kpmcore-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove HTML docs
    rm -rf $installdir/usr/share/doc
