name       : partitionmanager
version    : 20.12.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/partitionmanager-20.12.1.tar.xz : c52ca719f31e00e4fe33b98404d862a561d374380565112d65b8562da09ad7ff
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(libatasmart)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kpmcore-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove HTML docs
    rm -rf $installdir/usr/share/doc
