name       : partitionmanager
version    : 21.08.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/partitionmanager-21.08.1.tar.xz : e83fd797098e994f5222525cc6e5aa86a114f4f36191fd0ffacde88cc0036c9b
license    : GPL-3.0-or-later
component  : system.utils
summary    : KDE utility to help you manage disk devices
description: |
    KDE Partition Manager is a utility program to help you manage the disk devices, partitions and file systems on your computer. It allows you to easily create, copy, move, delete, resize without losing data, backup and restore partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(libatasmart)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kpmcore-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove HTML docs
    rm -rf $installdir/usr/share/doc
